config/routes.rb
Rails.application.routes.draw do

  root 'sessions#new'

  resources :sessions
  get '/signout' => "sessions#destroy"

  resources :borrowers

  resources :lenders
  post '/lenders/:id/lend' => 'lenders#lend'

end

app/models/borrower.rb
class Borrower < ActiveRecord::Base
	has_many :lenders, through: :historys
  attr_accessor :password, :password_confirmation

  email_regex = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]+)\z/i

  validates :first_name, :last_name,				:presence 		=> true,
  			                                        :length		    => { :maximum => 50 }
  			    										
  validates :email,		  							:presence		=> true,
  			    									:format		    => { :with => email_regex },
            										:uniqueness 	=> { :case_sensitive => false }

  validates :password, 								:presence 		=> true,
  	   		  										:confirmation 	=> true,
  			    									:length			=> { :within => 6..40 }

  before_save :encrypt_password

  def has_password?(submitted_password)
  	encrypted_password == encrypt(submitted_password)
  end

  # class method that checks whether the borrower's email and submitted_password are valid
  def self.authenticate(email, submitted_password)
  	borrower = find_by_email(email)

   	return nil if borrower.nil?

   	return borrower if borrower.has_password?(submitted_password)
  end

  private
  	def encrypt_password
  		# generate a unique salt if it's a new borrower
  		self.salt = Digest::SHA2.hexdigest("#{Time.now.utc}--#{password}") if self.new_record?
  	
  		# encrypt the password and store that in the encrypted_password field
  		self.encrypted_password = encrypt(password)
  	end

  	# encrypt the password using both the salt and the passed password
  	def encrypt(pass)
  		Digest::SHA2.hexdigest("#{self.salt}--#{pass}")
  	end

end

app/controllers/borrowers_controller.rb
class BorrowersController < ApplicationController
  before_action :set_borrower, only: [:show, :edit, :update, :destroy]

  # GET /borrowers
  # GET /borrowers.json
  def index
    @borrowers = Borrower.all
  end

  # GET /borrowers/1
  # GET /borrowers/1.json
  def show
    @history = History.where(borrower_id: session[:user_id])
  end

  # GET /borrowers/new
  def new
    @borrower = Borrower.new
  end

  # GET /borrowers/1/edit
  def edit
  end

  # POST /borrowers
  # POST /borrowers.json
  def create
    @borrower = Borrower.new(borrower_params)

    respond_to do |format|
      if @borrower.save
        format.html { redirect_to '/signout', notice: 'Borrower was successfully created.' }
        format.json { render :show, status: :created, location: @borrower }
      else
        format.html { render :new }
        format.json { render json: @borrower.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /borrowers/1
  # PATCH/PUT /borrowers/1.json
  def update
    respond_to do |format|
      if @borrower.update(borrower_params)
        format.html { redirect_to @borrower, notice: 'Borrower was successfully updated.' }
        format.json { render :show, status: :ok, location: @borrower }
      else
        format.html { render :edit }
        format.json { render json: @borrower.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /borrowers/1
  # DELETE /borrowers/1.json
  def destroy
    @borrower.destroy
    respond_to do |format|
      format.html { redirect_to borrowers_url, notice: 'Borrower was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_borrower
      @borrower = Borrower.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def borrower_params
      params.require(:borrower).permit(:first_name, :last_name, :email, :password, :password_confirmation, :money, :purpose, :description, :raised, :created_at, :updated_at)
    end
end

app/helpers/borrowers_helper.rb
module BorrowersHelper
end

app/views/borrowers/_form.html.erb
<%= form_for(@borrower) do |f| %>
  <% if @borrower.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@borrower.errors.count, "error") %> prohibited this borrower from being saved:</h2>

      <ul>
      <% @borrower.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.text_field :password_confirmation %>
  </div>
  <div class="field">
    <%= f.label :money %><br>
    <%= f.number_field :money %>
  </div>
  <div class="field">
    <%= f.label :purpose %><br>
    <%= f.text_field :purpose %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :raised %><br>
    <%= f.number_field :raised %>
  </div>
  <div class="field">
    <%= f.hidden_field :lender, :value => 'lender' %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/borrowers/edit.html.erb
<h1>Editing Borrower</h1>

<%= render 'form' %>

<%= link_to 'Show', @borrower %> |
<%= link_to 'Back', borrower_path %>

app/views/borrowers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Borrowers</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Money</th>
      <th>Purpose</th>
      <th>Description</th>
      <th>Raised</th>
      <th>Created at</th>
      <th>Updated at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @borrowers.each do |borrower| %>
      <tr>
        <td><a href="/borrowers/<%= borrower.id %>"><%= borrower.first_name %></a></td>
        <td><a href="/borrowers/<%= borrower.id %>"><%= borrower.last_name %></a></td>
        <td><%= borrower.email %></td>
        <td><%= borrower.money %></td>
        <td><%= borrower.purpose %></td>
        <td><%= borrower.description %></td>
        <td><%= borrower.raised %></td>
        <td><%= borrower.created_at %></td>
        <td><%= borrower.updated_at %></td>
        <td><%= link_to 'Show', borrower %></td>
        <td><%= link_to 'Edit', edit_borrower_path(borrower) %></td>
        <td><%= link_to 'Destroy', borrower, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/borrowers/new.html.erb
<p class="button"><%= link_to 'Back', '/' %></p>
<h1>New Borrower</h1>

<%= render 'form' %>

app/views/borrowers/show.html.erb
<link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.3/themes/smoothness/jquery-ui.css" />
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.3/jquery-ui.min.js"></script>
<script type="text/javascript">
$(document).ready(function(){
  $('.table_info').hide();
  $('#listing_lenders').hover(function(){
    $('.table_info').slideDown();
  });
});
</script>
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @borrower.first_name+" "+@borrower.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @borrower.email %>
</p>

<p>
  <strong>Initial asking:</strong>
  $<%= @borrower.money %>
</p>

<p>
  <strong>Purpose:</strong>
  <%= @borrower.purpose %>
</p>

<p>
  <strong>Description:</strong>
  <%= @borrower.description %>
</p>

<p>
  <strong>Money Raised:</strong>
  $<%= @borrower.raised %>
</p>

<h1 class="button" id="listing_lenders">Listing Lenders</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Money Lent</th>
    </tr>
  </thead>

  <tbody class="table_info">
    <% @history.each do |history| %>
      <tr>
        <td><%= history.lender.first_name+" "+history.lender.last_name %></td>
        <td><%= history.lender.email %></td>
        <td>$<%= history.amount %></td>
      </tr>
    <% end %>
  </tbody>
</table>