config/routes.rb
Rails.application.routes.draw do

  root 'sessions#new'

  resources :sessions
  get '/signout' => "sessions#destroy"

  resources :borrowers

  resources :lenders
  post '/lenders/:id/lend' => 'lenders#lend'

end

app/models/lender.rb
class Lender < ActiveRecord::Base
  has_many :borrowers, through: :historys
  attr_accessor :password, :password_confirmation

  email_regex = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]+)\z/i

  validates :first_name, :last_name,				:presence 		=> true,
  			                                        :length		    => { :maximum => 50 }
  			    										
  validates :email,		  							:presence		=> true,
  			    									:format		    => { :with => email_regex },
            										:uniqueness 	=> { :case_sensitive => false }

  validates :password, 								:presence 		=> true,
  	   		  										:confirmation 	=> true,
  			    									:length			=> { :within => 6..40 }

  before_save :encrypt_password

  def has_password?(submitted_password)
  	encrypted_password == encrypt(submitted_password)
  end

  # class method that checks whether the lender's email and submitted_password are valid
  def self.authenticate(email, submitted_password)
  	lender = find_by_email(email)

   	return nil if lender.nil?
   	return lender if lender.has_password?(submitted_password)
  end


  private
  	def encrypt_password
  		# generate a unique salt if it's a new lender
  		self.salt = Digest::SHA2.hexdigest("#{Time.now.utc}--#{password}") if self.new_record?
  	
  		# encrypt the password and store that in the encrypted_password field
  		self.encrypted_password = encrypt(password)
  	end

  	# encrypt the password using both the salt and the passed password
  	def encrypt(pass)
  		Digest::SHA2.hexdigest("#{self.salt}--#{pass}")
  	end

end

app/controllers/lenders_controller.rb
class LendersController < ApplicationController
  before_action :set_lender, only: [:show, :edit, :update, :destroy]

  # GET /lenders
  # GET /lenders.json
  def index
    @lenders = Lender.all
  end

  # GET /lenders/1
  # GET /lenders/1.json
  def show
    @history_lent_to = History.where(lender_id: session[:user_id])
    @borrowers = Borrower.all
    @lender1 = Lender.find(params[:id])
  end

  def lend
    @borrower_lent_to = History.new(amount: params[:lend], lender_id: session[:user_id], borrower_id: params[:id])
    @borrower_lent_to.save

    puts ''
    puts '@borrower_lent_to: '+@borrower_lent_to.amount.to_s+" "+@borrower_lent_to.lender.first_name.to_s+" "+@borrower_lent_to.borrower.first_name.to_s
    puts ''

    @borrower_lent = Borrower.find(params[:id])
    puts ''
    puts '@borrower_lent.raised: '+@borrower_lent.raised.to_s
    puts ''

    @amount = @borrower_lent.raised.to_i

    @amount = (@amount+@borrower_lent_to.amount.to_i)
    puts ''
    puts '@borrower_lent.raised: '+@borrower_lent.raised.to_s
    puts ''

    @add_lent_to_borrower = Borrower.where(id: params[:id]).update_all(raised: @amount)

    @Lender_lending = Lender.find(session[:user_id])
    puts ''
    puts '@Lender_lending.money: '+@Lender_lending.money.to_s
    puts ''

    @amount = @Lender_lending.money.to_i

    @amount = (@amount-@borrower_lent_to.amount.to_i)
    puts ''
    puts '@Lender_lending.money: '+@Lender_lending.money.to_s
    puts ''

    @spent_money = Lender.where(id: session[:user_id]).update_all(money: @amount)

    redirect_to :back
  end

  # GET /lenders/new
  def new
    @lender = Lender.new
  end

  # GET /lenders/1/edit
  def edit
  end

  # POST /lenders
  # POST /lenders.json
  def create
    @lender = Lender.new(lender_params)

    respond_to do |format|
      if @lender.save
        format.html { redirect_to '/signout', notice: 'Lender was successfully created.' }
        format.json { render :show, status: :created, location: @lender }
      else
        format.html { render :new }
        format.json { render json: @lender.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lenders/1
  # PATCH/PUT /lenders/1.json
  def update
    respond_to do |format|
      if @lender.update(lender_params)
        format.html { redirect_to @lender, notice: 'Lender was successfully updated.' }
        format.json { render :show, status: :ok, location: @lender }
      else
        format.html { render :edit }
        format.json { render json: @lender.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lenders/1
  # DELETE /lenders/1.json
  def destroy
    @lender.destroy
    respond_to do |format|
      format.html { redirect_to lenders_url, notice: 'Lender was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lender
    #   # @lender = Lender.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lender_params
      params.require(:lender).permit(:first_name, :last_name, :email, :password, :password_confirmation, :money, :created_at, :updated_at)
    end
end

app/helpers/lenders_helper.rb
module LendersHelper
end

app/views/lenders/_form.html.erb
<%= form_for(@lender) do |f| %>
  <% if @lender.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lender.errors.count, "error") %> prohibited this lender from being saved:</h2>

      <ul>
      <% @lender.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.text_field :password_confirmation %>
  </div>
  <div class="field">
    <%= f.label :money %><br>
    <%= f.number_field :money %>
  </div>
  <div class="field">
    <%= f.hidden_field :borrower, :value => 'borrower' %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lenders/edit.html.erb
<h1>Editing Lender</h1>

<%= render 'form' %>

<%= link_to 'Show', @lender %> |
<%= link_to 'Back', lender_path %>

app/views/lenders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Lenders</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Salt</th>
      <th>Money</th>
      <th>Created at</th>
      <th>Updated at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lenders.each do |lender| %>
      <tr>
        <td><a href="/lenders/<%= lender.id %>"><%= lender.first_name %></a></td>
        <td><a href="/lenders/<%= lender.id %>"><%= lender.last_name %></a></td>
        <td><%= lender.email %></td>
        <td><%= lender.money %></td>
        <td><%= lender.created_at %></td>
        <td><%= lender.updated_at %></td>
        <td><%= link_to 'Show', lender %></td>
        <td><%= link_to 'Edit', edit_lender_path(lender) %></td>
        <td><%= link_to 'Destroy', lender, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/lenders/new.html.erb
<p class="button"><%= link_to 'Back', '/' %></p>
<h1>New Lender</h1>

<%= render 'form' %>

app/views/lenders/show.html.erb
<link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.3/themes/smoothness/jquery-ui.css" />
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.3/jquery-ui.min.js"></script>
<script type="text/javascript">
$(document).ready(function(){
  $('#in_need_info').hide();
  $('#lent_to_info').hide();
  $('#borrowers_in_need').hover(function(){
    $('#in_need_info').slideDown();
  });
  $('#borrowers_lent_to').hover(function(){
    $('#lent_to_info').slideDown();
  });
});
</script>
<p id="notice"><%= notice %></p>
<div id="user_info">
  <p>
    <strong>Name:</strong>
    <%= @lender1.first_name+" "+@lender1.last_name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= @lender1.email %>
  </p>

  <p>
    <strong>Account Amount:</strong>
    $<%= @lender1.money %>
  </p>

  <p>
    <strong>Created at:</strong>
    <%= @lender1.created_at %>
  </p>

  <p>
    <strong>Updated at:</strong>
    <%= @lender1.updated_at %>
  </p>
</div>

<h1 class="button" id="borrowers_in_need">Borrowers that need help:</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Money Goal</th>
      <th>Purpose</th>
      <th>Description</th>
      <th>Raised</th>
      <th>Created at</th>
      <th>Updated at</th>
      <th>Action</th>
    </tr>
  </thead>

  <tbody id="in_need_info">
    <% @borrowers.each do |borrower| %>
      <tr>
        <td><%= borrower.first_name+" "+borrower.last_name %></td>
        <td><%= borrower.email %></td>
        <td>$<%= borrower.money %></td>
        <td><%= borrower.purpose %></td>
        <td><%= borrower.description %></td>
        <td>$<%= borrower.raised %></td>
        <td><%= borrower.created_at %></td>
        <td><%= borrower.updated_at %></td>
        <td>
          <form action="/lenders/<%= borrower.id %>/lend" method="post">
            $<input type="number" name="lend">
            <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
            <input class="button" type="submit" value="Lend">
          </form><%=  %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<h1 class="button" id="borrowers_lent_to">Borrowers that you lent to:</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Need Money for</th>
      <th>Reason for Loan</th>
      <th>Email</th>
      <th>Amount Needed</th>
      <th>I gave</th>
      <th>Date</th>
    </tr>
  </thead>

  <tbody id="lent_to_info">
    <% @history_lent_to.each do |history| %>
      <tr>
        <td><%= history.borrower.first_name+" "+history.borrower.last_name %></td>
        <td><%= history.borrower.purpose %></td>
        <td><%= history.borrower.description %></td>
        <td><%= history.borrower.email %></td>
        <td>$<%= history.borrower.money %></td>
        <td>$<%= history.amount %></td>
        <td>$<%= history.created_at %></td>

      </tr>
    <% end %>
  </tbody>
</table>